"""
PySpark Connect client.

Loads the persistent RSA private key from jwt-private-key.pem (generated by
create-jwt-token.py), mints a short-lived JWT, attaches it to the Spark
Connect connection string, and exercises the full auth + S3 write flow:

  JWT → gRPC header → JwtExtractInterceptor → JwtAuth.validateToken()
      → gRPC Context → CredentialInjectionRule → auth-service → STS creds
      → Hadoop S3A config → write Parquet to s3proxy (localhost:9090)

Prerequisites
-------------
  1. python create-jwt-token.py          # generate jwt-private-key.pem
  2. docker compose -f docker-compose.s3proxy.yml up -d   # start s3proxy
  3. uv run python auth-service.py       # start mock auth service
  4. spark-submit ... local[*]           # start Spark Connect server

Usage
-----
    uv run python pyspark-client.py
"""

#%%

import datetime
import jwt
from cryptography.hazmat.primitives.serialization import load_pem_private_key
from pyspark.sql import SparkSession
from pyspark.sql import functions as F

# ---------------------------------------------------------------------------
# 1. Load the persistent private key and mint a short-lived JWT.
#    The server validates the signature against jwt-public-key.pem.
#    Run create-jwt-token.py once to generate both key files.
# ---------------------------------------------------------------------------
print("Loading private key from jwt-private-key.pem and minting JWT...")
with open("jwt-private-key.pem", "rb") as f:
    private_key = load_pem_private_key(f.read(), password=None)

now = datetime.datetime.utcnow()
payload = {
    "iss": "http://localhost:5556/dex",
    "sub": "user-001",
    "email": "dataengineer@example.com",
    "aud": "spark-client",
    "iat": now,
    "exp": now + datetime.timedelta(hours=1),
}
token = jwt.encode(payload, private_key, algorithm="RS256")
print(f"JWT minted (prefix={token[:16]}...)")

# # ---------------------------------------------------------------------------
# # 2. Connect to Spark Connect with the JWT as the bearer token.
# #    The token= parameter in the connection string is sent as the
# #    Authorization: Bearer <token> gRPC metadata header.
# # ---------------------------------------------------------------------------
SPARK_CONNECT_URL = f"sc://localhost:15002/;token={token}"
# SPARK_CONNECT_URL = f"sc://localhost:15002/"
print(f"\nConnecting to Spark Connect at sc://localhost:15002/ ...")

spark = (
    SparkSession.builder
    .remote(SPARK_CONNECT_URL)
    .getOrCreate()
)
print("Connected.\n")

# ---------------------------------------------------------------------------
# 3. Point S3A at the local s3proxy (localhost:9090).
#    Credentials (access key / secret key / session token) are NOT set here —
#    CredentialInjectionRule injects them server-side on the first query by
#    calling auth-service.py.  We only need to tell S3A where the endpoint is.
# ---------------------------------------------------------------------------
S3_ENDPOINT    = "http://host.docker.internal:9090"
S3_BUCKET      = "poc-data"
S3_OUTPUT_PATH = f"s3a://{S3_BUCKET}/word-count/"

spark.conf.set("spark.hadoop.fs.s3a.endpoint",                  S3_ENDPOINT)
spark.conf.set("spark.hadoop.fs.s3a.path.style.access",         "true")
spark.conf.set("spark.hadoop.fs.s3a.connection.ssl.enabled",    "false")
spark.conf.set("spark.hadoop.fs.s3a.bucket.probe",              "0")
# s3proxy does not support the bulk DeleteObjects API; disable it so S3A falls
# back to single-object deletes (avoids 501 Not Implemented on overwrite/delete).
spark.conf.set("spark.hadoop.fs.s3a.multiobjectdelete.enable",  "false")

# ---------------------------------------------------------------------------
# 4. Hello-world calculation: sum of 1..10
#    This is the first query — CredentialInjectionRule fires here and calls
#    auth-service to fetch STS credentials, then injects them into Hadoop config.
# ---------------------------------------------------------------------------
print("=== Hello World: sum of 1 to 10 ===")
df = spark.range(1, 11)
result = df.select(F.sum("id").alias("total")).collect()[0]["total"]
print(f"Sum of 1..10 = {result}")
assert result == 55, f"Expected 55, got {result}"

# ---------------------------------------------------------------------------
# 5. Word count — written as Parquet to s3proxy
# ---------------------------------------------------------------------------
print(f"\n=== Word count → Parquet → {S3_OUTPUT_PATH} ===")
words = spark.createDataFrame(
    [("hello world",), ("hello spark",), ("spark connect",)],
    ["line"],
)
counts = (
    words
    .select(F.explode(F.split("line", " ")).alias("word"))
    .groupBy("word")
    .count()
    .orderBy("word")
)
counts.show()

print(f"Writing Parquet to {S3_OUTPUT_PATH} ...")
counts.write.mode("overwrite").parquet(S3_OUTPUT_PATH)
print("Write complete.")

# ---------------------------------------------------------------------------
# 6. Read back and verify
# ---------------------------------------------------------------------------
print(f"\nReading Parquet back from {S3_OUTPUT_PATH} ...")
readback = spark.read.parquet(S3_OUTPUT_PATH)
readback.orderBy("word").show()
assert readback.count() == counts.count(), "Row count mismatch after read-back"
print("Read-back verified.")

print("\nAll checks passed.")
spark.stop()